### ISSUE TITLE
MKNetworkKit is not checking validity of SSL certificates

### ISSUE THREAD

**Issue by YDing** [MugunthKumar/MKNetworkKit#192]
I have found that when the certificate is the wrong certificate for the domain, MKNetworkKit still allows the request to complete.  This should not be the case.

Is this a configuration issue?

**Comment by linshi** [comment]
How is the recent update for SSL Pinning in MKNetworking ? Is that easy to implemented by implementing cert validating in willSendRequestForAuthenticationChallenge delegate of NSURLConnection ?

**Comment by shalomda** [comment]
Hi
Is there news with the ssl pinning?
