### ISSUE TITLE
Sometimes crash on checkAndRestoreFrozenOperations

### ISSUE THREAD

**Issue by tomsonxu** [MugunthKumar/MKNetworkKit#209]
Test environment: 3rd gen iPad with iOS 6

Sometimes app crashes when  run MKNetworkKit. Following is error log
objc_msgsend exc_bad_access
checkAndRestoreFrozenOperations exc_bad_access

Is it a bug?

**Comment by brucewangzhihua** [comment]
@tomsonxu Why close the issue? How do you resolve the problem?
